# Generated by Django 4.1.1 on 2022-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeding', '0003_vegetablesort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vegetablesort',
            options={'ordering': ['time_create', 'name'], 'verbose_name': 'Сорт', 'verbose_name_plural': 'Сорт овощей'},
        ),
        migrations.AlterField(
            model_name='vegetablesort',
            name='distanceBetweenBushes',
            field=models.PositiveIntegerField(verbose_name='Дистанция между кустов'),
        ),
        migrations.AlterField(
            model_name='vegetablesort',
            name='distanceBetweenRows',
            field=models.PositiveIntegerField(verbose_name='Дистанция между рядов'),
        ),
    ]
