# Generated by Django 4.1.1 on 2022-09-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeding', '0004_alter_vegetablesort_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetablesort',
            name='vegetable',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='seeding.vegetable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vegetablesort',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Сорт овощей'),
        ),
    ]
