# Generated by Django 4.1.1 on 2022-09-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeding', '0005_vegetablesort_vegetable_alter_vegetablesort_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablesort',
            name='vegetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='seeding.vegetable'),
        ),
    ]
