"""empty message

Revision ID: 02701a64f6e8
Revises: 
Create Date: 2023-03-02 21:12:47.858323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02701a64f6e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overview_of_houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('settlement_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_adress', sa.String(length=500), nullable=False),
    sa.Column('main_image', sa.String(length=1000), nullable=False),
    sa.Column('video_zen', sa.String(length=1000), nullable=True),
    sa.Column('video_rutube', sa.String(length=1000), nullable=True),
    sa.Column('link_to_ads', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('area_of_house', sa.Integer(), nullable=False),
    sa.Column('plot_area', sa.Integer(), nullable=False),
    sa.Column('bathroom_in_house', sa.Boolean(), nullable=False),
    sa.Column('gaz', sa.Boolean(), nullable=False),
    sa.Column('created_ad', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_foreign_key(None, 'districts', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'link', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'news', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'settlements', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'settlements', 'settlement_types', ['settlement_types_id'], ['id'])
    op.create_foreign_key(None, 'settlements', 'districts', ['district_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_constraint(None, 'districts', type_='foreignkey')
    op.drop_table('overview_of_houses')
    op.drop_table('users')
    op.drop_table('role')
    # ### end Alembic commands ###
