"""empty message

Revision ID: 8bc30003096a
Revises: 02701a64f6e8
Create Date: 2023-03-02 21:41:12.055950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bc30003096a'
down_revision = '02701a64f6e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'districts', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'link', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'news', 'categories', ['category_id'], ['id'])
    op.alter_column('overview_of_houses', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'overview_of_houses', 'settlements', ['settlement_id'], ['id'])
    op.create_foreign_key(None, 'overview_of_houses', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'overview_of_houses', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(None, 'settlements', 'settlement_types', ['settlement_types_id'], ['id'])
    op.create_foreign_key(None, 'settlements', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(None, 'settlements', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint(None, 'overview_of_houses', type_='foreignkey')
    op.drop_constraint(None, 'overview_of_houses', type_='foreignkey')
    op.drop_constraint(None, 'overview_of_houses', type_='foreignkey')
    op.alter_column('overview_of_houses', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_constraint(None, 'districts', type_='foreignkey')
    # ### end Alembic commands ###
